# Site settings
title: AltraVia 
subtitle: "From Aspiration to Achievement: Biomedical Careers in India and Abroad"
email: info@altraviants.org
description: > # this means to ignore newlines until "baseurl:"
    Empowering biomedical journeys across education, research, and careers - bridging aspirations with opportunities in India and worldwide.
    Book your free consultation today.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://altraviants.org" # the base hostname & protocol for your site

# User setting
owner: Neema T S
email: 
facebook_username:
twitter_username:
github_username: altravia-nts
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:


# Build settings
markdown: kramdown

include:

  - "_content"
